{% set name = "openff-forcefields" %}
{% set version = "2024.03.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-forcefields/archive/{{ version }}.tar.gz
  sha256: 4c99a94db2348738d22ffc20e59b4c12367c0fec21e67f3a1173c8b64429010e
 
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.9
    - setuptools
  run_constrained:
    - openforcefields ==9999999999
test:
  requires:
    - openff-toolkit
  imports:
    - openforcefields
  files:
    - test.py
  commands:
    - python test.py

about:
  home: https://openforcefield.org/
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: Force fields released by the Open Force Field Initiative.
  description: |
    The provided OFFXML (force field) files are successive versions
    of a general-purpose small molecule force field, written in the
    SMIRNOFF format; this force field should cover all or almost all
    of drug-like chemical space, and illustrate some of the major
    functionality of the SMIRNOFF format as well as how it simplifies
    the specification of force field parameters in a compact and
    chemically sensible way.
  doc_url: https://github.com/openforcefield/openff-forcefields
  dev_url: https://github.com/openforcefield/openff-forcefields

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - j-wags
    - mattwthompson
    - simonboothroyd
    - lilyminium
