{% set name = "openff-forcefields" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-forcefields/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: efbf2427e8c6c7ee9d01fe2c019985b3cf40220af02ae4bb6ac9c7501c50eca3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - setuptools
  run_constrained:
    - openforcefields ==9999999999

test:
  imports:
    - openforcefields

about:
  home: https://openforcefield.org/
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: Force fields released by the Open Force Field Initiative.
  description: |
    The provided OFFXML (force field) files are successive versions
    of a general-purpose small molecule force field, written in the
    SMIRNOFF format; this force field should cover all or almost all
    of drug-like chemical space, and illustrate some of the major
    functionality of the SMIRNOFF format as well as how it simplifies
    the specification of force field parameters in a compact and
    chemically sensible way.
  doc_url: https://github.com/openforcefield/openff-forcefields
  dev_url: https://github.com/openforcefield/openff-forcefields

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - j-wags
    - mattwthompson
    - simonboothroyd
